config/routes.rb
Rails.application.routes.draw do
  get 'report/index'

  get 'tell_more/index'

  get 'visualize/index'

  get 'visualize/report'

  root 'homepage#index'
  get 'homepage/signin'

  devise_for :clients, :controllers => {:registrations => "clients/registrations"}
  get 'dashboard/index' => 'dashboard#index'
  resources :events
  get 'dashboard/add_event' => 'dashboard#add_event'
  get 'signed_in' => 'homepage#signed_in'
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    if(client_signed_in?)
      redirect_to '/dashboard/index'
    end
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/index.html.erb
<%= stylesheet_link_tag "uikit" %>

<div class="uk-container uk-container-center uk-margin-top">
  <div class="uk-panel uk-panel-box uk-text-center">
    <h1>Welcome to Full:Fill!</h1>
    <h2>Live your life in full!</h2>

    <p>Capture the activities in your life, organize them by personality facets and traits, and visualize them in a model to learn about yourself and others.</p>
    <br/>

    <p>Fill out the facets of your life less visited for a well-rounded character and experience.</p>
    <%= link_to "Register", new_client_registration_path, :method => :get, class: 'uk-button uk-button-primary uk-button-large' %>
    <%= link_to "Fill in my activities", new_client_session_path, :method => :get, class: 'uk-button uk-button-primary uk-button-large' %>
    <%= link_to "Visualize my life", visualize_index_path, class: 'uk-button uk-button-primary uk-button-large' %>
    <%= link_to "Tell me more", tell_more_index_path, class: 'uk-button uk-button-primary uk-button-large' %>
    <%= link_to "Log In", new_client_session_path, :method => :get, class: 'uk-button uk-button-success uk-button-large' %>
  </div>
</div>