config/routes.rb
Rails.application.routes.draw do
  get 'report/index'

  get 'tell_more/index'

  get 'visualize/index'

  get 'visualize/report'

  root 'homepage#index'
  get 'homepage/signin'

  devise_for :clients, :controllers => {:registrations => "clients/registrations"}
  get 'dashboard/index' => 'dashboard#index'
  resources :events
  get 'dashboard/add_event' => 'dashboard#add_event'
  get 'signed_in' => 'homepage#signed_in'
end

app/controllers/dashboard_controller.rb
require 'date'
require 'wice_grid'

class DashboardController < ApplicationController
  include DashboardHelper
  attr_accessor :client_ID

  def index
    if(!client_signed_in?)
      redirect_to '/'
    end

    @client_ID = current_client.id
    @person = Person.find_by(client_id: current_client.id)
    flash[:success] = 'Welcome, ' + @person.name_first + ' to the Dashboard!'

    calcAllEvents
  end

  def add_event
    redirect_to '/events/new'
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def calcAllEvents
    @events = Event.where(person_id: @person.id)
    @person_grid = initialize_grid(@events, order: 'events.activity_when', order_direction: 'desc')

    @physical = nil
    @expressive = nil
    @creative = nil
    @abstract = nil
    @social = nil

    @physScore = 0
    @expresScore = 0
    @creatScore = 0
    @abstractScore = 0
    @socialScore = 0

    @numOfActivityColumns = 4

    calc_age_range
    input_events
    calc_scores
    getTopThreeEvents
  end

  def getTopThreeEvents
    @sortedEvents = @events.sort_by { |obj| obj.activity_hours }.reverse
    @topEvent = @sortedEvents[0];
    @secondEvent = @sortedEvents[1];
  end

  def input_events
    ageModeArray = []

    @events.each do |event|
      ageModeArray.push(event.activity_when)
    end
  end

  def calc_age_range
    @ageArr = []
    @birthYear = Date.strptime(@person.birth_date, "%m/%d/%Y").year.to_i
    @currentYear = Date.today.year.to_i

    @difference = @currentYear - @birthYear

    for i in 0..@difference do
      @ageArr[i] = i
    end
  end

  def calc_scores
    @events.each do |event|
      activity_spec = Activity.where(activity_spec_id: event.activity_id).first
      trait_spec = Trait.where(trait_spec_id: activity_spec.trait_id).first
      facet_spec = Facet.where(id: trait_spec.facet_id).first

      if(facet_spec.facettype == "physical")
        @physScore = @physScore + event.activity_hours
      end
      if(facet_spec.facettype == "expressive")
        @expresScore = @expresScore + event.activity_hours
      end
      if(facet_spec.facettype == "creative")
        @creatScore = @creatScore + event.activity_hours
      end
      if(facet_spec.facettype == "abstract")
        @abstractScore = @abstractScore + event.activity_hours
      end
      if(facet_spec.facettype == "social")
        @socialScore = @socialScore + event.activity_hours
      end
    end
  end
end

app/views/dashboard/index.html.erb
<script type="text/javascript" src="https://static.fusioncharts.com/code/latest/fusioncharts.js"></script>
<script type="text/javascript" src="https://static.fusioncharts.com/code/latest/themes/fusioncharts.theme.fint.js?cacheBust=56"></script>

<h1><%= @person.name_first %>'s Dashboard</h1>
<%= link_to "Log Out", destroy_client_session_path, :method => :delete, class: 'uk-button-danger uk-button uk-button-large' %>
<%= link_to "Add Event", 'add_event', class: 'uk-button uk-button-small' %>
<%= link_to "Report", report_index_path, class: 'uk-button uk-button-small' %>
<%= link_to "Visualize", visualize_index_path, class: 'uk-button uk-button-small' %>

<br/><br/><br/>
<% if @events.length >= 2 %>
<span>For the activity "<%= Activity.find_by_activity_spec_id(@topEvent.activity_id).activityname.downcase %>", you have <%= @topEvent.activity_hours %> out of ten thousand hours to become a master
  <div class="uk-progress uk-progress-success" style="width: 550px;">
    <div class="uk-progress-bar" style="width: <%= @topEvent.activity_hours / 100%>%;"> <%= @topEvent.activity_hours / 100%>%</div>
  </div>
</span>
<span>For the activity "<%= Activity.find_by_activity_spec_id(@secondEvent.activity_id).activityname.downcase %>", you have <%= @secondEvent.activity_hours %> out of ten thousand hours to become a master
  <div class="uk-progress uk-progress-warning" style="width: 550px;">
    <div class="uk-progress-bar" style="width: <%= @secondEvent.activity_hours / 100%>%;"> <%= @secondEvent.activity_hours / 100%>%</div>
  </div>
</span>
<% end %>
<%= grid(@person_grid) do |g|

  g.column name: 'Activity Name', attribute: 'activity_id' do |act|
    Activity.where(activity_spec_id: act.activity_id).first.activityname.split.map(&:capitalize).join(' ')
  end

  g.column name: 'Hours', attribute: 'activity_hours'
  g.column name: 'Note', attribute: 'activity_note'
  g.column name: 'Place', attribute: 'activity_place'
  g.column name: 'Age', attribute: 'activity_when'

  g.column do |task|
    # link_to('Delete', destroy_client_session_path(task))
  end
end -%>


<%= javascript_tag do %>

    FusionCharts.ready(function(){
      var fusioncharts = new FusionCharts({
      type: 'radar',
      renderAt: 'chart-container',
      width: '500',
      height: '350',
      dataFormat: 'json',
      dataSource: {
        "chart": {
        "caption": "Personality Map",
        "subCaption": "Your own personality",
        "numberPreffix": "$",
        "theme": "fint",
        "radarfillcolor": "#ffffff",
        },
        "categories": [{
          "category": [{"label": "Physical"}, {"label": "Social"}, {"label": "Abstract"},
                      {"label": "Creative"}, {"label": "Expressive"}]}],
        "dataset": [{
          "seriesname": "Facets",
            "data": [{
              "value": "<%= raw @person.physical_score.to_s %>"
            }, {
              "value": "<%= raw @person.social_score.to_s %>"
            }, {
              "value": "<%= raw @person.abstract_score.to_s %>"
            }, {
              "value": "<%= raw @person.creative_score.to_s %>"
            }, {
              "value": "<%= raw @person.expressive_score.to_s %>"
            }]
          }]
        }
      }
    );
    fusioncharts.render();
    });

<% end %>

<body>
<div id="chart-container"></div>
</body>

app/views/dashboard/index.html.haml
.well
  %h2= current_page_title
  %p
    The
    %code name
    parameter adds names of columns to the grid.

= show_code

.row-fluid
  .col-md-12
    = render   'grid'