config/routes.rb
Rails.application.routes.draw do
  get 'report/index'

  get 'tell_more/index'

  get 'visualize/index'

  get 'visualize/report'

  root 'homepage#index'
  get 'homepage/signin'

  devise_for :clients, :controllers => {:registrations => "clients/registrations"}
  get 'dashboard/index' => 'dashboard#index'
  resources :events
  get 'dashboard/add_event' => 'dashboard#add_event'
  get 'signed_in' => 'homepage#signed_in'
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_one :activity
  # attr_accessable :person_id, :activity_hours, :activity_note, :activity_place, :activity_when
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new(person_id: current_client.id)
    @person = Person.find_by(client_id: current_client.id)
    @activities = Activity.all
    @activityIDs = []
    @activityNames = []
    @activities.each do |item|
      @activityIDs << item.activity_spec_id
      @activityNames << item.activityname
    end
    @hours = 0
  end

  # GET /events/1/edit
  def edit
    @person = Person.find_by(client_id: current_client.id)
  end

  # POST /events
  # POST /events.json
  def create
    @person = Person.find_by(client_id: current_client.id)
    @activities = Activity.all
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to '/dashboard/index', notice: 'Event was successfully created.' }
      else
        format.html { render :new }
      end
    end

    activity_spec = Activity.where(activity_spec_id: @event.activity_id).first
    trait_spec = Trait.where(trait_spec_id: activity_spec.trait_id).first
    facettype = Facet.where(id: trait_spec.facet_id).first.facettype
    if(facettype == 'physical') then
      score = @person.physical_score.to_i + @event.activity_hours.to_i
      @person.update_column(:physical_score, score)
    elsif(facettype == 'expressive') then
      score = @person.expressive_score.to_i + @event.activity_hours.to_i
      @person.update_column(:expressive_score, score)
    elsif(facettype == 'creative') then
      score = @person.creative_score.to_i + @event.activity_hours.to_i
      @person.update_column(:creative_score, score)
    elsif(facettype == 'abstract') then
      score = @person.abstract_score.to_i + @event.activity_hours.to_i
      @person.update_column(:abstract_score, score)
    elsif(facettype == 'social') then
      score = @person.social_score.to_i + @event.activity_hours.to_i
      @person.update_column(:social_score, score)
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:activity_id, :activity_hours, :activity_note, :activity_place, :activity_when, :person_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <!-- 1 hr unreported -->
    <!-- Add a button that goes to a page that displays all possible activities -->
    <%= f.input :activity_id, :as => :hidden %>
    <%= f.input :activityname, required: true, label: 'Activity Name', wrapper_html: {class: 'ui-widget' } %>
    <%= f.input :activity_hours, as: :float, required: true, label: 'How many hours did you do this activity for?', :input_html => {:value => 0}%>
    <div onclick="return mathHelp()" class="uk-button uk-button-danger uk-button-small">Week to Year</div>
    <%= f.input :activity_note, required: false, label: 'Activity note? ' %>
    <%= f.input :activity_place, required: false, label: 'Where did you do this activity? ' %>
    <%= f.input :activity_when, as: :integer, required: true,  label: 'What age were you? ' %>
    <%= f.input :person_id, :as => :hidden, :input_html => { :value => @person.client_id } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= javascript_tag do %>
    function mathHelp() {
      var hoursPerWeek = prompt("How many hours per week?", "0");
      var hours = 0;
      var totalHours = 0;
      hours = parseFloat(hoursPerWeek);
      if(hours != null) {
        totalHours = hours * 52;
      }
      document.getElementById("event_activity_hours").value = totalHours;
    return;
    }
<% end %>

<%= javascript_tag do %>
    function inputID() {
      var id = 0;
      var name = document.getElementById("event_activityname").value;
      var index = availableInputs.indexOf(name);
      id = availableIDs[index];
      document.getElementById("event_activity_id").value = id;
    }

<% end %>

<%= javascript_tag "availableInputs = #{@activityNames.to_json.html_safe};" %>
<%= javascript_tag "availableIDs = #{@activityIDs.to_json.html_safe};" %>

<%= javascript_tag do %>
$(function() {
  $("#event_activityname").autocomplete({
    source: availableInputs,
    close: function(event, ui) {}
    });
});
$("#event_activityname").on("autocompleteclose", function(event, ui) { inputID(); });
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboard_index_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>